### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by HelgaListopad** [kilosha/test_task#1]
Hi! There are a couple of issues to improve: 

1. Sizing: 
- The `width` of the datatable/form is fixed. As a result, UI does not fit narrow screens/browser windows: the list shrinks to 0, the form and a part of the datatable are overflowing the available space.
Relative sizing is more appropriate. It would be also good to limit the minimum width of the form and list. Both features are [mentioned here](https://docs.webix.com/desktop__dimensions.html) (check the article for `gravity` and `minWidth`).

2. Styling: 
- Removing background from `webix_transparent` seems to be unnecessary.
- `border: none` for list items removes borders and therefore changes the height of an item. Sizing logic in Webix is implemented in JS, so these extra changes [will not be recognized](https://docs.webix.com/desktop__styling.html#wherecsscanandcannotbeapplied). This may be an issue on a big dataset (improper scroll position, unexpected result of auto-sizing, etc.). A `transparent` colour for an item's border is always safe.

A side note (not really a problem).
In addition to inputs that represent certain values, it's OK to place other components (buttons, templates, etc.) into the form. 
```js
  elements:[
    {  view:"template", template:"Edit films", type:"section" },
    /* inputs */
    buttons,
    {}
  ]
```
This would allow shortening the hierarchy of `rows` and set paddings only at one level.

**Comment by kilosha** [comment]
Hello. Thanks for the review. I fixed all the indicated issues.

**Comment by HelgaListopad** [comment]
Great, thank you!
